/* Automatically generated by dapto: DO NOT EDIT */

#ifdef MONITOR
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "dapto_dapto.h"


#ifdef PROTO_OK
void _dapto_init (int pid)
#else
void _dapto_init (pid)
    int pid;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("init");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (pid);
#else
    DAPTO_RESULT_OTHER (pid);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_finit ()
#else
void _dapto_finit ()
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("finit");
    DAPTO_RESULT_LONGVAL (clock ());
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_exit ()
#else
void _dapto_exit ()
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("exit");
    DAPTO_RESULT_LONGVAL (clock ());
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_stopped (const char * locale, int error)
#else
void _dapto_stopped (locale, error)
    const char * locale;
    int error;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("stopped");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (locale);
#else
    DAPTO_RESULT_OTHER (locale);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (error);
#else
    DAPTO_RESULT_OTHER (error);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_enter (const char * name)
#else
void _dapto_enter (name)
    const char * name;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("enter");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_leave (const char * name)
#else
void _dapto_leave (name)
    const char * name;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("leave");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
    DAPTO_RESULT_SEND (0);
}

void _dap_dapto_init ()
{
}
#else
static int _dapto; /* To avoid messages about empty files. */
#endif
