/* Automatically generated by dapto: DO NOT EDIT */

#ifdef MONITOR
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "attr_mon_dapto.h"


#ifdef PROTO_OK
void get_symb_attrsCmd (char *args)
#else
void get_symb_attrsCmd (args)
    char *args;
#endif
{
    int root;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARG_INT (&root);
    DAPTO_INIT_OP;
/* #line 13 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/attr_mon.dapto.16209018.cpp" */
{ switch (LHSMAP[(MONTblStackArray(root))->_prod]) {
	case SYMBVariableDeclList:
		break;
	case SYMBStatementList:
		break;
	case SYMBAxiom:
		break;
	case SYMBOptInitialize:
		break;
	case SYMBVarIdList:
		break;
	case SYMBVariableDeclSeg:
		DAPTO_RESULT_STR ("type tOilType");
		break;
	case SYMBParameterDecl:
		break;
	case SYMBVariableDecl:
		break;
	case SYMBUnop:
		DAPTO_RESULT_STR ("operator tOilOp");
		DAPTO_RESULT_STR ("indication tOilOp");
		break;
	case SYMBBinop:
		DAPTO_RESULT_STR ("operator tOilOp");
		DAPTO_RESULT_STR ("indication tOilOp");
		break;
	case SYMBNotop:
		DAPTO_RESULT_STR ("operator tOilOp");
		DAPTO_RESULT_STR ("indication tOilOp");
		break;
	case SYMBShortCircuitOp:
		DAPTO_RESULT_STR ("operator tOilOp");
		DAPTO_RESULT_STR ("indication tOilOp");
		break;
	case SYMBParameterList:
		break;
	case SYMBResultType:
		DAPTO_RESULT_STR ("type tOilType");
		break;
	case SYMBWhileStmt:
		DAPTO_RESULT_STR ("ContinueLbl DefTableKey");
		DAPTO_RESULT_STR ("BreakLbl DefTableKey");
		break;
	case SYMBExpression:
		DAPTO_RESULT_STR ("possible tOilTypeSet");
		DAPTO_RESULT_STR ("yields tOilType");
		break;
	case SYMBStatement:
		break;
	case SYMBCompound:
		DAPTO_RESULT_STR ("Env Environment");
		break;
	case SYMBProgram:
		DAPTO_RESULT_STR ("Env Environment");
		DAPTO_RESULT_STR ("type tOilType");
		DAPTO_RESULT_STR ("ContinueLbl DefTableKey");
		DAPTO_RESULT_STR ("BreakLbl DefTableKey");
		break;
	case SYMBIdUse:
		DAPTO_RESULT_STR ("Key DefTableKey");
		DAPTO_RESULT_STR ("Sym int");
		break;
	case SYMBIdDef:
		DAPTO_RESULT_STR ("Key DefTableKey");
		DAPTO_RESULT_STR ("Sym int");
		break;
	default: DAPTO_RESULT_STR ("unknown node type");
}}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_rule_attrsCmd (char *args)
#else
void get_rule_attrsCmd (args)
    char *args;
#endif
{
    int root;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARG_INT (&root);
    DAPTO_INIT_OP;
/* #line 85 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/attr_mon.dapto.16209018.cpp" */
{ switch ((MONTblStackArray(root))->_prod) {
	case RULErule_15:
		break;
	case RULErule_14:
		break;
	case RULErule_13:
		break;
	case RULErule_12:
		break;
	case RULErule_11:
		break;
	case RULErule_10:
		break;
	case RULErule_9:
		break;
	case RULErule_8:
		break;
	case RULErule_7:
		break;
	case RULErule_6:
		break;
	case RULErule_5:
		break;
	case RULErule_4:
		break;
	case RULErule_3:
		break;
	case RULErule_2:
		break;
	case RULErule_1:
		break;
	case RULEMonadicExp:
		break;
	case RULEDyadicExp:
		break;
	case RULEIdnVal:
		break;
	case RULEFloatVal:
		break;
	case RULEIntVal:
		break;
	case RULEFloatParDecl:
		break;
	case RULEIntParDecl:
		break;
	case RULEInitialize:
		break;
	case RULEVarDecl:
		break;
	case RULEFloatVar:
		break;
	case RULEIntVar:
		break;
	case RULEUMinusOp:
		break;
	case RULEPercentOp:
		break;
	case RULESlashOp:
		break;
	case RULEStarOp:
		break;
	case RULEMinusOp:
		break;
	case RULEPlusOp:
		break;
	case RULEGreaterOp:
		break;
	case RULELessOp:
		break;
	case RULEEqualOp:
		break;
	case RULEExclOp:
		break;
	case RULENotExp:
		break;
	case RULEAmpOp:
		break;
	case RULEBarOp:
		break;
	case RULEShortCircuitExp:
		break;
	case RULECondExp:
		break;
	case RULEAssignExp:
		DAPTO_RESULT_STR ("possible tOilTypeSet");
		DAPTO_RESULT_STR ("operator tOilOp");
		break;
	case RULEExprStmt:
		break;
	case RULEFloatResult:
		break;
	case RULEIntResult:
		break;
	case RULESource:
		break;
	case RULEReturnStmt:
		DAPTO_RESULT_STR ("operator tOilOp");
		break;
	case RULEContinueStmt:
		break;
	case RULEBreakStmt:
		break;
	case RULELoop:
		break;
	case RULETwoSided:
		break;
	case RULEOneSided:
		break;
	case RULEAppliedOccurrence:
		break;
	case RULEDefiningOccurrence:
		break;
	default: DAPTO_RESULT_STR ("unknown node type");
}}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_rule_termsCmd (char *args)
#else
void get_rule_termsCmd (args)
    char *args;
#endif
{
    int root;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARG_INT (&root);
    DAPTO_INIT_OP;
/* #line 203 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/attr_mon.dapto.16209018.cpp" */
{ switch ((MONTblStackArray(root))->_prod) {
	case RULEAssignExp:
		break;
	case RULECondExp:
		break;
	case RULEShortCircuitExp:
		break;
	case RULENotExp:
		break;
	case RULEIntVal:
		DAPTO_RESULT_STR ("IntDenotation int");
		break;
	case RULEFloatVal:
		DAPTO_RESULT_STR ("FloatDenotation int");
		break;
	case RULEIdnVal:
		break;
	case RULEDyadicExp:
		break;
	case RULEMonadicExp:
		break;
	case RULEDefiningOccurrence:
		DAPTO_RESULT_STR ("Identifier int");
		break;
	case RULEOneSided:
		break;
	case RULETwoSided:
		break;
	case RULELoop:
		break;
	case RULEBreakStmt:
		break;
	case RULEContinueStmt:
		break;
	case RULEReturnStmt:
		break;
	case RULESource:
		DAPTO_RESULT_STR ("Identifier int");
		break;
	case RULEExprStmt:
		break;
	case RULEBarOp:
		break;
	case RULEAmpOp:
		break;
	case RULEExclOp:
		break;
	case RULEEqualOp:
		break;
	case RULELessOp:
		break;
	case RULEGreaterOp:
		break;
	case RULEPlusOp:
		break;
	case RULEMinusOp:
		break;
	case RULEStarOp:
		break;
	case RULESlashOp:
		break;
	case RULEPercentOp:
		break;
	case RULEUMinusOp:
		break;
	case RULEIntVar:
		break;
	case RULEFloatVar:
		break;
	case RULEVarDecl:
		break;
	case RULEInitialize:
		break;
	case RULEIntParDecl:
		break;
	case RULEFloatParDecl:
		break;
	case RULErule_2:
		break;
	case RULErule_3:
		break;
	case RULErule_4:
		break;
	case RULErule_5:
		break;
	case RULErule_6:
		break;
	case RULErule_7:
		break;
	case RULErule_8:
		break;
	case RULErule_9:
		break;
	case RULErule_10:
		break;
	case RULErule_11:
		break;
	case RULErule_12:
		break;
	case RULErule_13:
		break;
	case RULErule_14:
		break;
	case RULErule_15:
		break;
	case RULEAppliedOccurrence:
		DAPTO_RESULT_STR ("Identifier int");
		break;
	case RULEIntResult:
		break;
	case RULEFloatResult:
		break;
	case RULErule_1:
		break;
	default: DAPTO_RESULT_STR ("unknown node type");
}}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void _dapto_term_int (int root, const char * name, int value)
#else
void _dapto_term_int (root, name, value)
    int root;
    const char * name;
    int value;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("term_int");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_int (int root, int is_symb, const char * name, int value, int line, int col)
#else
void _dapto_attr_int (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    int value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_int");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_POSITION (int root, int is_symb, const char * name, POSITION value, int line, int col)
#else
void _dapto_attr_POSITION (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    POSITION value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_POSITION");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTPOSITION
    DAPTO_RESULTPOSITION (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_NODEPTR (int root, int is_symb, const char * name, NODEPTR value, int line, int col)
#else
void _dapto_attr_NODEPTR (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    NODEPTR value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_NODEPTR");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTNODEPTR
    DAPTO_RESULTNODEPTR (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_tOilOp (int root, int is_symb, const char * name, tOilOp value, int line, int col)
#else
void _dapto_attr_tOilOp (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    tOilOp value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_tOilOp");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTtOilOp
    DAPTO_RESULTtOilOp (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_tOilTypeSet (int root, int is_symb, const char * name, tOilTypeSet value, int line, int col)
#else
void _dapto_attr_tOilTypeSet (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    tOilTypeSet value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_tOilTypeSet");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTtOilTypeSet
    DAPTO_RESULTtOilTypeSet (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_tOilType (int root, int is_symb, const char * name, tOilType value, int line, int col)
#else
void _dapto_attr_tOilType (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    tOilType value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_tOilType");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTtOilType
    DAPTO_RESULTtOilType (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_DefTableKey (int root, int is_symb, const char * name, DefTableKey value, int line, int col)
#else
void _dapto_attr_DefTableKey (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    DefTableKey value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_DefTableKey");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTDefTableKey
    DAPTO_RESULTDefTableKey (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_attr_Environment (int root, int is_symb, const char * name, Environment value, int line, int col)
#else
void _dapto_attr_Environment (root, is_symb, name, value, line, col)
    int root;
    int is_symb;
    const char * name;
    Environment value;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("attr_Environment");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (is_symb);
#else
    DAPTO_RESULT_OTHER (is_symb);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULTEnvironment
    DAPTO_RESULTEnvironment (value);
#else
    DAPTO_RESULT_OTHER (value);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_computation (int root, int line, int col)
#else
void _dapto_computation (root, line, col)
    int root;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("computation");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void _dapto_void_comp (int root, const char * name, int line, int col)
#else
void _dapto_void_comp (root, name, line, col)
    int root;
    const char * name;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("void_comp");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (root);
#else
    DAPTO_RESULT_OTHER (root);
#endif
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (name);
#else
    DAPTO_RESULT_OTHER (name);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

void _dap_attr_mon_init ()
{
    _dap_add_command ("get_symb_attrs", get_symb_attrsCmd );
    _dap_add_command ("get_rule_attrs", get_rule_attrsCmd );
    _dap_add_command ("get_rule_terms", get_rule_termsCmd );
}
#else
static int _dapto; /* To avoid messages about empty files. */
#endif
