/* Automatically generated by dapto: DO NOT EDIT */

#ifdef MONITOR
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "cola_dapto.h"


#ifdef PROTO_OK
void _dapto_production (int prod, int uses, int linebeg, int colbeg, int lineend, int colend)
#else
void _dapto_production (prod, uses, linebeg, colbeg, lineend, colend)
    int prod;
    int uses;
    int linebeg;
    int colbeg;
    int lineend;
    int colend;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("production");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (prod);
#else
    DAPTO_RESULT_OTHER (prod);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (uses);
#else
    DAPTO_RESULT_OTHER (uses);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (linebeg);
#else
    DAPTO_RESULT_OTHER (linebeg);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (colbeg);
#else
    DAPTO_RESULT_OTHER (colbeg);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (lineend);
#else
    DAPTO_RESULT_OTHER (lineend);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (colend);
#else
    DAPTO_RESULT_OTHER (colend);
#endif
    DAPTO_RESULT_SEND (0);
}

#ifdef PROTO_OK
void get_conc_prodCmd (char *args)
#else
void get_conc_prodCmd (args)
    char *args;
#endif
{
    int index;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARG_INT (&index);
    DAPTO_INIT_OP;
/* #line 36 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/cola.dapto.16213306.cpp" */
{
    extern char *conc_prods[];

    DAPTO_RESULT_STR (conc_prods[index]);
}
    DAPTO_RESULT_SEND (1);
}

void _dap_cola_init ()
{
    _dap_add_command ("get_conc_prod", get_conc_prodCmd );
}
#else
static int _dapto; /* To avoid messages about empty files. */
#endif
