/* Automatically generated by dapto: DO NOT EDIT */

#ifdef MONITOR
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "clp_dapto.h"


#ifdef PROTO_OK
void _dapto_source_changed (const char * filename, int init, int curline, int curcol, int line, int col)
#else
void _dapto_source_changed (filename, init, curline, curcol, line, col)
    const char * filename;
    int init;
    int curline;
    int curcol;
    int line;
    int col;
#endif
{
    DAPTO_INIT_EV;
    DAPTO_RESULT_STR ("source_changed");
    DAPTO_RESULT_LONGVAL (clock ());
#ifdef DAPTO_RESULT_STR
    DAPTO_RESULT_STR (filename);
#else
    DAPTO_RESULT_OTHER (filename);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (init);
#else
    DAPTO_RESULT_OTHER (init);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (curline);
#else
    DAPTO_RESULT_OTHER (curline);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (curcol);
#else
    DAPTO_RESULT_OTHER (curcol);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (line);
#else
    DAPTO_RESULT_OTHER (line);
#endif
#ifdef DAPTO_RESULT_INT
    DAPTO_RESULT_INT (col);
#else
    DAPTO_RESULT_OTHER (col);
#endif
    DAPTO_RESULT_SEND (0);
}

void _dap_clp_init ()
{
}
#else
static int _dapto; /* To avoid messages about empty files. */
#endif
