/* Automatically generated by dapto: DO NOT EDIT */

#ifndef gla_DAPTO_H
#define gla_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
extern void _dap_gla_init ();
#ifdef PROTO_OK
extern void _dapto_token (const char *, int, int, int, int, int, int, const char *, int, int, int);
#else
extern void _dapto_token ();
#endif
#endif
