/* Automatically generated by dapto: DO NOT EDIT */

#ifdef MONITOR
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "oil_dapto.h"


#ifdef PROTO_OK
void get_oil_typeCmd (char *args)
#else
void get_oil_typeCmd (args)
    char *args;
#endif
{
    tOilType t;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilType (&t);
    DAPTO_INIT_OP;
/* #line 29 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{
  DAPTO_RESULTDefTableKey(t->sName);
  DAPTO_RESULTtOilCoercionSeq(t->sCoercionCosts);
}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_oil_opCmd (char *args)
#else
void get_oil_opCmd (args)
    char *args;
#endif
{
    tOilOp o;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilOp (&o);
    DAPTO_INIT_OP;
/* #line 37 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{ tOilArgSig s;
  DAPTO_RESULTDefTableKey(o->sName);
  DAPTO_RESULT_INT(o->sCost);
  for (s = o->sArgs; s != OilEmptyArgSig; s = s->sNext)
    DAPTO_RESULTtOilType(s->sArg);
}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_identificationsCmd (char *args)
#else
void get_identificationsCmd (args)
    char *args;
#endif
{
    tOilOp o;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilOp (&o);
    DAPTO_INIT_OP;
/* #line 47 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{ tOilOpIdentification s;
  for (s = o->sIndOps; s; s = s->sNext)
    DAPTO_RESULTtOilType(s->sOp);
}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_oil_type_setCmd (char *args)
#else
void get_oil_type_setCmd (args)
    char *args;
#endif
{
    tOilTypeSet ts;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilTypeSet (&ts);
    DAPTO_INIT_OP;
/* #line 55 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{ 
  do {
    DAPTO_RESULTtOilType(ts->sBaseType);
    DAPTO_RESULT_INT(ts->sCost);
    ts = ts->sNext;
  } while (ts != OilEmptyTypeSet);
}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_oil_set_sigCmd (char *args)
#else
void get_oil_set_sigCmd (args)
    char *args;
#endif
{
    tOilSetSig ts;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilSetSig (&ts);
    DAPTO_INIT_OP;
/* #line 66 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{ 
  do {
    DAPTO_RESULTtOilTypeSet(ts->head);
    ts = ts->tail;
  } while (ts != OilEmptySetSig);
}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_oil_arg_sigCmd (char *args)
#else
void get_oil_arg_sigCmd (args)
    char *args;
#endif
{
    tOilArgSig ts;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilArgSig (&ts);
    DAPTO_INIT_OP;
/* #line 76 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{ 
  do {
    DAPTO_RESULTtOilType(ts->sArg);
    ts = ts->sNext;
  } while (ts != OilEmptyArgSig);
}
    DAPTO_RESULT_SEND (1);
}

#ifdef PROTO_OK
void get_oil_coercion_seqCmd (char *args)
#else
void get_oil_coercion_seqCmd (args)
    char *args;
#endif
{
    tOilCoercionSeq cs;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGtOilCoercionSeq (&cs);
    DAPTO_INIT_OP;
/* #line 86 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/oil.dapto.16207138.cpp" */
{ 
  do {
    DAPTO_RESULTtOilType(cs->sResultType);
    DAPTO_RESULTint(cs->sCost);
    cs = cs->sNextCost;
  } while (cs);
}
    DAPTO_RESULT_SEND (1);
}

void _dap_oil_init ()
{
    _dap_add_command ("get_oil_type", get_oil_typeCmd );
    _dap_add_command ("get_oil_op", get_oil_opCmd );
    _dap_add_command ("get_identifications", get_identificationsCmd );
    _dap_add_command ("get_oil_type_set", get_oil_type_setCmd );
    _dap_add_command ("get_oil_set_sig", get_oil_set_sigCmd );
    _dap_add_command ("get_oil_arg_sig", get_oil_arg_sigCmd );
    _dap_add_command ("get_oil_coercion_seq", get_oil_coercion_seqCmd );
}
#else
static int _dapto; /* To avoid messages about empty files. */
#endif
