/* Automatically generated by dapto: DO NOT EDIT */

#ifndef cola_DAPTO_H
#define cola_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
extern void _dap_cola_init ();
#ifdef PROTO_OK
extern void _dapto_production (int, int, int, int, int, int);
#else
extern void _dapto_production ();
#endif
#endif
