/* Automatically generated by dapto: DO NOT EDIT */

#ifndef attr_mon_DAPTO_H
#define attr_mon_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
#include "node.h"
#include "nodecode.h"
#include "eliproto.h"
#include "MONTblStack.h"
extern void _dap_attr_mon_init ();
#ifdef PROTO_OK
extern void _dapto_term_int (int, const char *, int);
#else
extern void _dapto_term_int ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_int (int, int, const char *, int, int, int);
#else
extern void _dapto_attr_int ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_POSITION (int, int, const char *, POSITION, int, int);
#else
extern void _dapto_attr_POSITION ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_NODEPTR (int, int, const char *, NODEPTR, int, int);
#else
extern void _dapto_attr_NODEPTR ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_tOilOp (int, int, const char *, tOilOp, int, int);
#else
extern void _dapto_attr_tOilOp ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_tOilTypeSet (int, int, const char *, tOilTypeSet, int, int);
#else
extern void _dapto_attr_tOilTypeSet ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_tOilType (int, int, const char *, tOilType, int, int);
#else
extern void _dapto_attr_tOilType ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_DefTableKey (int, int, const char *, DefTableKey, int, int);
#else
extern void _dapto_attr_DefTableKey ();
#endif
#ifdef PROTO_OK
extern void _dapto_attr_Environment (int, int, const char *, Environment, int, int);
#else
extern void _dapto_attr_Environment ();
#endif
#ifdef PROTO_OK
extern void _dapto_computation (int, int, int);
#else
extern void _dapto_computation ();
#endif
#ifdef PROTO_OK
extern void _dapto_void_comp (int, const char *, int, int);
#else
extern void _dapto_void_comp ();
#endif
#endif
