/* Automatically generated by dapto: DO NOT EDIT */

#ifndef liga_DAPTO_H
#define liga_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
#include "eliproto.h"
#include "err.h"
#include "obstack.h"
#include "node.h"
#include "MONTblStack.h"
extern void _dap_liga_init ();
#ifdef PROTO_OK
extern void _dapto_tree (int, int, int);
#else
extern void _dapto_tree ();
#endif
#endif
