/* Automatically generated by dapto: DO NOT EDIT */

#ifndef clp_DAPTO_H
#define clp_DAPTO_H
#include "dapto.h"
#include "eliproto.h"
extern void _dap_clp_init ();
#ifdef PROTO_OK
extern void _dapto_source_changed (const char *, int, int, int, int, int);
#else
extern void _dapto_source_changed ();
#endif
#endif
