export ODINBOOT; ODINBOOT=1
export ODINBOOT_CONFIG; ODINBOOT_CONFIG=1
export ODINBOOT_SOCKET_LIBS; ODINBOOT_SOCKET_LIBS=''
export ODINBOOT_SOCKET_LIBS_PRM; ODINBOOT_SOCKET_LIBS_PRM=""
export ODIN_CC; ODIN_CC=gcc
export ODIN_CC_FLAGS; ODIN_CC_FLAGS='-g -O2'
