/* Automatically generated by dapto: DO NOT EDIT */

#ifdef MONITOR
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "pdl_dapto.h"


#ifdef PROTO_OK
void get_propertiesCmd (char *args)
#else
void get_propertiesCmd (args)
    char *args;
#endif
{
    DefTableKey key;
    DAPTO_ARG_INIT_OP;
    DAPTO_ARGDefTableKey (&key);
    DAPTO_INIT_OP;
/* #line 29 "/home/lukem/Dropbox/CAS/eli-4.8.1/CACHE/lukem-Inspiron-N7010/FILES/k/v/pdl.dapto.16203906.cpp" */
{
    pdl_mon_properties (key);
}
    DAPTO_RESULT_SEND (1);
}

void _dap_pdl_init ()
{
    _dap_add_command ("get_properties", get_propertiesCmd );
}
#else
static int _dapto; /* To avoid messages about empty files. */
#endif
